servidor:
  restart: always
  build: ./Servidor
  expose:
    - "8080"
  ports:
    - "8080:8080"
  links:
    - database:database
  env_file: .env
  
database:
  restart: always
  build: ./Database
  ports:
    - "5432:5432" 
  env_file: .env
